spring:
  application:
      name: service-auth-client


#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#
#    bus:
#      trace:
#        enabled: true
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka
  instance:
      lease-expiration-duration-in-seconds: 30
      lease-renewal-interval-in-seconds: 10

server:
    port: 8084
management.security.enabled: false

security:
  oauth2:
    resource:
      id: service-auth-client
      user-info-uri: http://localhost:8090/server-auth/user
      prefer-token-info: false






