server:
  port: 8888
spring:
  application:
    name: cloudserver
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/@profileActive@-properties/
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/