spring:
  application:
    name: server-gateway

server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://docker-compose-eureka:8761/eureka/

zuul:
  routes:
    demo-api-a:
      serviceId: cloud-service-a
      path: /**
    demo-api-b:
      serviceId: cloud-service-b
      path: /**
    server-auth:
      path: /server-auth/**
      sensitiveHeaders:
      serviceId: server-auth
    service-auth-client:
        path: /order/**
        sensitiveHeaders:
        serviceId: service-auth-client
  add-proxy-headers: true
security:
  oauth2:
    client:
      access-token-uri: http://localhost:8090/server-auth/oauth/token
      user-authorization-uri: http://localhost:8090/server-auth/oauth/authorize
      client_id: webapp
      client_secret: webapp
    resource:
      user-info-uri: http://localhost:8090/server-auth/user
      prefer-token-info: false

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 70000


ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
