server:
  port: 8081
  servlet:
    context-path: /cloudClient

url: 47.89.17.7

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    statusPageUrlPath: ${server.servlet.context-path}/info
    healthCheckUrlPath: ${server.servlet.context-path}/health
#    prefer-ip-address: true
#    ip-address: 101.132.75.75
    #发送心跳间隔时间
    lease-renewal-interval-in-seconds: 3
    #服务时效后注销时间
    lease-expiration-duration-in-seconds: 3